// This file was generated by the 'generate' Rake task

package htmlbuffer

func (b *HtmlBuffer) Base(attrs Attrs) {
	b.WriteVoidElement("base", attrs)
}

func (b *HtmlBuffer) Base_() {
	b.WriteVoidElement("base", nil)
}

func (b *HtmlBuffer) Link(attrs Attrs) {
	b.WriteVoidElement("link", attrs)
}

func (b *HtmlBuffer) Link_() {
	b.WriteVoidElement("link", nil)
}

func (b *HtmlBuffer) Meta(attrs Attrs) {
	b.WriteVoidElement("meta", attrs)
}

func (b *HtmlBuffer) Meta_() {
	b.WriteVoidElement("meta", nil)
}

func (b *HtmlBuffer) Hr(attrs Attrs) {
	b.WriteVoidElement("hr", attrs)
}

func (b *HtmlBuffer) Hr_() {
	b.WriteVoidElement("hr", nil)
}

func (b *HtmlBuffer) Br(attrs Attrs) {
	b.WriteVoidElement("br", attrs)
}

func (b *HtmlBuffer) Br_() {
	b.WriteVoidElement("br", nil)
}

func (b *HtmlBuffer) Wbr(attrs Attrs) {
	b.WriteVoidElement("wbr", attrs)
}

func (b *HtmlBuffer) Wbr_() {
	b.WriteVoidElement("wbr", nil)
}

func (b *HtmlBuffer) Input(attrs Attrs) {
	b.WriteVoidElement("input", attrs)
}

func (b *HtmlBuffer) Input_() {
	b.WriteVoidElement("input", nil)
}

func (b *HtmlBuffer) Area(attrs Attrs) {
	b.WriteVoidElement("area", attrs)
}

func (b *HtmlBuffer) Area_() {
	b.WriteVoidElement("area", nil)
}

func (b *HtmlBuffer) Command(attrs Attrs) {
	b.WriteVoidElement("command", attrs)
}

func (b *HtmlBuffer) Command_() {
	b.WriteVoidElement("command", nil)
}

func (b *HtmlBuffer) Col(attrs Attrs) {
	b.WriteVoidElement("col", attrs)
}

func (b *HtmlBuffer) Col_() {
	b.WriteVoidElement("col", nil)
}

func (b *HtmlBuffer) Img(attrs Attrs) {
	b.WriteVoidElement("img", attrs)
}

func (b *HtmlBuffer) Img_() {
	b.WriteVoidElement("img", nil)
}

func (b *HtmlBuffer) Keygen(attrs Attrs) {
	b.WriteVoidElement("keygen", attrs)
}

func (b *HtmlBuffer) Keygen_() {
	b.WriteVoidElement("keygen", nil)
}

func (b *HtmlBuffer) Param(attrs Attrs) {
	b.WriteVoidElement("param", attrs)
}

func (b *HtmlBuffer) Param_() {
	b.WriteVoidElement("param", nil)
}

func (b *HtmlBuffer) Source(attrs Attrs) {
	b.WriteVoidElement("source", attrs)
}

func (b *HtmlBuffer) Source_() {
	b.WriteVoidElement("source", nil)
}

func (b *HtmlBuffer) Track(attrs Attrs) {
	b.WriteVoidElement("track", attrs)
}

func (b *HtmlBuffer) Track_() {
	b.WriteVoidElement("track", nil)
}

func (b *HtmlBuffer) Embed(attrs Attrs) {
	b.WriteVoidElement("embed", attrs)
}

func (b *HtmlBuffer) Embed_() {
	b.WriteVoidElement("embed", nil)
}

