// This file was generated by the 'generate' Rake task

package htmlwriter

func (w *HtmlWriter) Html(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("html", attrs, innerHtml)
}

func (w *HtmlWriter) Html_(innerHtml func()) {
	w.WriteNormalElement("html", nil, innerHtml)
}

func (w *HtmlWriter) Head(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("head", attrs, innerHtml)
}

func (w *HtmlWriter) Head_(innerHtml func()) {
	w.WriteNormalElement("head", nil, innerHtml)
}

func (w *HtmlWriter) Style(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("style", attrs, innerHtml)
}

func (w *HtmlWriter) Style_(innerHtml func()) {
	w.WriteNormalElement("style", nil, innerHtml)
}

func (w *HtmlWriter) Script(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("script", attrs, innerHtml)
}

func (w *HtmlWriter) Script_(innerHtml func()) {
	w.WriteNormalElement("script", nil, innerHtml)
}

func (w *HtmlWriter) Noscript(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("noscript", attrs, innerHtml)
}

func (w *HtmlWriter) Noscript_(innerHtml func()) {
	w.WriteNormalElement("noscript", nil, innerHtml)
}

func (w *HtmlWriter) Body(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("body", attrs, innerHtml)
}

func (w *HtmlWriter) Body_(innerHtml func()) {
	w.WriteNormalElement("body", nil, innerHtml)
}

func (w *HtmlWriter) Section(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("section", attrs, innerHtml)
}

func (w *HtmlWriter) Section_(innerHtml func()) {
	w.WriteNormalElement("section", nil, innerHtml)
}

func (w *HtmlWriter) Nav(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("nav", attrs, innerHtml)
}

func (w *HtmlWriter) Nav_(innerHtml func()) {
	w.WriteNormalElement("nav", nil, innerHtml)
}

func (w *HtmlWriter) Article(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("article", attrs, innerHtml)
}

func (w *HtmlWriter) Article_(innerHtml func()) {
	w.WriteNormalElement("article", nil, innerHtml)
}

func (w *HtmlWriter) Aside(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("aside", attrs, innerHtml)
}

func (w *HtmlWriter) Aside_(innerHtml func()) {
	w.WriteNormalElement("aside", nil, innerHtml)
}

func (w *HtmlWriter) H1(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("h1", attrs, innerHtml)
}

func (w *HtmlWriter) H1_(innerHtml func()) {
	w.WriteNormalElement("h1", nil, innerHtml)
}

func (w *HtmlWriter) H2(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("h2", attrs, innerHtml)
}

func (w *HtmlWriter) H2_(innerHtml func()) {
	w.WriteNormalElement("h2", nil, innerHtml)
}

func (w *HtmlWriter) H3(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("h3", attrs, innerHtml)
}

func (w *HtmlWriter) H3_(innerHtml func()) {
	w.WriteNormalElement("h3", nil, innerHtml)
}

func (w *HtmlWriter) H4(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("h4", attrs, innerHtml)
}

func (w *HtmlWriter) H4_(innerHtml func()) {
	w.WriteNormalElement("h4", nil, innerHtml)
}

func (w *HtmlWriter) H5(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("h5", attrs, innerHtml)
}

func (w *HtmlWriter) H5_(innerHtml func()) {
	w.WriteNormalElement("h5", nil, innerHtml)
}

func (w *HtmlWriter) H6(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("h6", attrs, innerHtml)
}

func (w *HtmlWriter) H6_(innerHtml func()) {
	w.WriteNormalElement("h6", nil, innerHtml)
}

func (w *HtmlWriter) Header(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("header", attrs, innerHtml)
}

func (w *HtmlWriter) Header_(innerHtml func()) {
	w.WriteNormalElement("header", nil, innerHtml)
}

func (w *HtmlWriter) Footer(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("footer", attrs, innerHtml)
}

func (w *HtmlWriter) Footer_(innerHtml func()) {
	w.WriteNormalElement("footer", nil, innerHtml)
}

func (w *HtmlWriter) Address(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("address", attrs, innerHtml)
}

func (w *HtmlWriter) Address_(innerHtml func()) {
	w.WriteNormalElement("address", nil, innerHtml)
}

func (w *HtmlWriter) Main(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("main", attrs, innerHtml)
}

func (w *HtmlWriter) Main_(innerHtml func()) {
	w.WriteNormalElement("main", nil, innerHtml)
}

func (w *HtmlWriter) P(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("p", attrs, innerHtml)
}

func (w *HtmlWriter) P_(innerHtml func()) {
	w.WriteNormalElement("p", nil, innerHtml)
}

func (w *HtmlWriter) Pre(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("pre", attrs, innerHtml)
}

func (w *HtmlWriter) Pre_(innerHtml func()) {
	w.WriteNormalElement("pre", nil, innerHtml)
}

func (w *HtmlWriter) Blockquote(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("blockquote", attrs, innerHtml)
}

func (w *HtmlWriter) Blockquote_(innerHtml func()) {
	w.WriteNormalElement("blockquote", nil, innerHtml)
}

func (w *HtmlWriter) Ol(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("ol", attrs, innerHtml)
}

func (w *HtmlWriter) Ol_(innerHtml func()) {
	w.WriteNormalElement("ol", nil, innerHtml)
}

func (w *HtmlWriter) Ul(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("ul", attrs, innerHtml)
}

func (w *HtmlWriter) Ul_(innerHtml func()) {
	w.WriteNormalElement("ul", nil, innerHtml)
}

func (w *HtmlWriter) Li(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("li", attrs, innerHtml)
}

func (w *HtmlWriter) Li_(innerHtml func()) {
	w.WriteNormalElement("li", nil, innerHtml)
}

func (w *HtmlWriter) Dl(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("dl", attrs, innerHtml)
}

func (w *HtmlWriter) Dl_(innerHtml func()) {
	w.WriteNormalElement("dl", nil, innerHtml)
}

func (w *HtmlWriter) Dt(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("dt", attrs, innerHtml)
}

func (w *HtmlWriter) Dt_(innerHtml func()) {
	w.WriteNormalElement("dt", nil, innerHtml)
}

func (w *HtmlWriter) Dd(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("dd", attrs, innerHtml)
}

func (w *HtmlWriter) Dd_(innerHtml func()) {
	w.WriteNormalElement("dd", nil, innerHtml)
}

func (w *HtmlWriter) Figure(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("figure", attrs, innerHtml)
}

func (w *HtmlWriter) Figure_(innerHtml func()) {
	w.WriteNormalElement("figure", nil, innerHtml)
}

func (w *HtmlWriter) Figcaption(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("figcaption", attrs, innerHtml)
}

func (w *HtmlWriter) Figcaption_(innerHtml func()) {
	w.WriteNormalElement("figcaption", nil, innerHtml)
}

func (w *HtmlWriter) Div(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("div", attrs, innerHtml)
}

func (w *HtmlWriter) Div_(innerHtml func()) {
	w.WriteNormalElement("div", nil, innerHtml)
}

func (w *HtmlWriter) A(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("a", attrs, innerHtml)
}

func (w *HtmlWriter) A_(innerHtml func()) {
	w.WriteNormalElement("a", nil, innerHtml)
}

func (w *HtmlWriter) Em(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("em", attrs, innerHtml)
}

func (w *HtmlWriter) Em_(innerHtml func()) {
	w.WriteNormalElement("em", nil, innerHtml)
}

func (w *HtmlWriter) Strong(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("strong", attrs, innerHtml)
}

func (w *HtmlWriter) Strong_(innerHtml func()) {
	w.WriteNormalElement("strong", nil, innerHtml)
}

func (w *HtmlWriter) Small(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("small", attrs, innerHtml)
}

func (w *HtmlWriter) Small_(innerHtml func()) {
	w.WriteNormalElement("small", nil, innerHtml)
}

func (w *HtmlWriter) S(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("s", attrs, innerHtml)
}

func (w *HtmlWriter) S_(innerHtml func()) {
	w.WriteNormalElement("s", nil, innerHtml)
}

func (w *HtmlWriter) Cite(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("cite", attrs, innerHtml)
}

func (w *HtmlWriter) Cite_(innerHtml func()) {
	w.WriteNormalElement("cite", nil, innerHtml)
}

func (w *HtmlWriter) Q(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("q", attrs, innerHtml)
}

func (w *HtmlWriter) Q_(innerHtml func()) {
	w.WriteNormalElement("q", nil, innerHtml)
}

func (w *HtmlWriter) Dfn(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("dfn", attrs, innerHtml)
}

func (w *HtmlWriter) Dfn_(innerHtml func()) {
	w.WriteNormalElement("dfn", nil, innerHtml)
}

func (w *HtmlWriter) Abbr(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("abbr", attrs, innerHtml)
}

func (w *HtmlWriter) Abbr_(innerHtml func()) {
	w.WriteNormalElement("abbr", nil, innerHtml)
}

func (w *HtmlWriter) Data(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("data", attrs, innerHtml)
}

func (w *HtmlWriter) Data_(innerHtml func()) {
	w.WriteNormalElement("data", nil, innerHtml)
}

func (w *HtmlWriter) Time(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("time", attrs, innerHtml)
}

func (w *HtmlWriter) Time_(innerHtml func()) {
	w.WriteNormalElement("time", nil, innerHtml)
}

func (w *HtmlWriter) Code(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("code", attrs, innerHtml)
}

func (w *HtmlWriter) Code_(innerHtml func()) {
	w.WriteNormalElement("code", nil, innerHtml)
}

func (w *HtmlWriter) Var(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("var", attrs, innerHtml)
}

func (w *HtmlWriter) Var_(innerHtml func()) {
	w.WriteNormalElement("var", nil, innerHtml)
}

func (w *HtmlWriter) Samp(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("samp", attrs, innerHtml)
}

func (w *HtmlWriter) Samp_(innerHtml func()) {
	w.WriteNormalElement("samp", nil, innerHtml)
}

func (w *HtmlWriter) Kbd(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("kbd", attrs, innerHtml)
}

func (w *HtmlWriter) Kbd_(innerHtml func()) {
	w.WriteNormalElement("kbd", nil, innerHtml)
}

func (w *HtmlWriter) Sub(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("sub", attrs, innerHtml)
}

func (w *HtmlWriter) Sub_(innerHtml func()) {
	w.WriteNormalElement("sub", nil, innerHtml)
}

func (w *HtmlWriter) Sup(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("sup", attrs, innerHtml)
}

func (w *HtmlWriter) Sup_(innerHtml func()) {
	w.WriteNormalElement("sup", nil, innerHtml)
}

func (w *HtmlWriter) I(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("i", attrs, innerHtml)
}

func (w *HtmlWriter) I_(innerHtml func()) {
	w.WriteNormalElement("i", nil, innerHtml)
}

func (w *HtmlWriter) B(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("b", attrs, innerHtml)
}

func (w *HtmlWriter) B_(innerHtml func()) {
	w.WriteNormalElement("b", nil, innerHtml)
}

func (w *HtmlWriter) U(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("u", attrs, innerHtml)
}

func (w *HtmlWriter) U_(innerHtml func()) {
	w.WriteNormalElement("u", nil, innerHtml)
}

func (w *HtmlWriter) Mark(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("mark", attrs, innerHtml)
}

func (w *HtmlWriter) Mark_(innerHtml func()) {
	w.WriteNormalElement("mark", nil, innerHtml)
}

func (w *HtmlWriter) Ruby(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("ruby", attrs, innerHtml)
}

func (w *HtmlWriter) Ruby_(innerHtml func()) {
	w.WriteNormalElement("ruby", nil, innerHtml)
}

func (w *HtmlWriter) Rt(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("rt", attrs, innerHtml)
}

func (w *HtmlWriter) Rt_(innerHtml func()) {
	w.WriteNormalElement("rt", nil, innerHtml)
}

func (w *HtmlWriter) Rp(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("rp", attrs, innerHtml)
}

func (w *HtmlWriter) Rp_(innerHtml func()) {
	w.WriteNormalElement("rp", nil, innerHtml)
}

func (w *HtmlWriter) Bdi(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("bdi", attrs, innerHtml)
}

func (w *HtmlWriter) Bdi_(innerHtml func()) {
	w.WriteNormalElement("bdi", nil, innerHtml)
}

func (w *HtmlWriter) Bdo(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("bdo", attrs, innerHtml)
}

func (w *HtmlWriter) Bdo_(innerHtml func()) {
	w.WriteNormalElement("bdo", nil, innerHtml)
}

func (w *HtmlWriter) Span(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("span", attrs, innerHtml)
}

func (w *HtmlWriter) Span_(innerHtml func()) {
	w.WriteNormalElement("span", nil, innerHtml)
}

func (w *HtmlWriter) Ins(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("ins", attrs, innerHtml)
}

func (w *HtmlWriter) Ins_(innerHtml func()) {
	w.WriteNormalElement("ins", nil, innerHtml)
}

func (w *HtmlWriter) Del(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("del", attrs, innerHtml)
}

func (w *HtmlWriter) Del_(innerHtml func()) {
	w.WriteNormalElement("del", nil, innerHtml)
}

func (w *HtmlWriter) Iframe(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("iframe", attrs, innerHtml)
}

func (w *HtmlWriter) Iframe_(innerHtml func()) {
	w.WriteNormalElement("iframe", nil, innerHtml)
}

func (w *HtmlWriter) Object(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("object", attrs, innerHtml)
}

func (w *HtmlWriter) Object_(innerHtml func()) {
	w.WriteNormalElement("object", nil, innerHtml)
}

func (w *HtmlWriter) Video(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("video", attrs, innerHtml)
}

func (w *HtmlWriter) Video_(innerHtml func()) {
	w.WriteNormalElement("video", nil, innerHtml)
}

func (w *HtmlWriter) Audio(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("audio", attrs, innerHtml)
}

func (w *HtmlWriter) Audio_(innerHtml func()) {
	w.WriteNormalElement("audio", nil, innerHtml)
}

func (w *HtmlWriter) Canvas(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("canvas", attrs, innerHtml)
}

func (w *HtmlWriter) Canvas_(innerHtml func()) {
	w.WriteNormalElement("canvas", nil, innerHtml)
}

func (w *HtmlWriter) Map(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("map", attrs, innerHtml)
}

func (w *HtmlWriter) Map_(innerHtml func()) {
	w.WriteNormalElement("map", nil, innerHtml)
}

func (w *HtmlWriter) Svg(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("svg", attrs, innerHtml)
}

func (w *HtmlWriter) Svg_(innerHtml func()) {
	w.WriteNormalElement("svg", nil, innerHtml)
}

func (w *HtmlWriter) Math(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("math", attrs, innerHtml)
}

func (w *HtmlWriter) Math_(innerHtml func()) {
	w.WriteNormalElement("math", nil, innerHtml)
}

func (w *HtmlWriter) Table(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("table", attrs, innerHtml)
}

func (w *HtmlWriter) Table_(innerHtml func()) {
	w.WriteNormalElement("table", nil, innerHtml)
}

func (w *HtmlWriter) Caption(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("caption", attrs, innerHtml)
}

func (w *HtmlWriter) Caption_(innerHtml func()) {
	w.WriteNormalElement("caption", nil, innerHtml)
}

func (w *HtmlWriter) Colgroup(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("colgroup", attrs, innerHtml)
}

func (w *HtmlWriter) Colgroup_(innerHtml func()) {
	w.WriteNormalElement("colgroup", nil, innerHtml)
}

func (w *HtmlWriter) Tbody(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("tbody", attrs, innerHtml)
}

func (w *HtmlWriter) Tbody_(innerHtml func()) {
	w.WriteNormalElement("tbody", nil, innerHtml)
}

func (w *HtmlWriter) Thead(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("thead", attrs, innerHtml)
}

func (w *HtmlWriter) Thead_(innerHtml func()) {
	w.WriteNormalElement("thead", nil, innerHtml)
}

func (w *HtmlWriter) Tfoot(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("tfoot", attrs, innerHtml)
}

func (w *HtmlWriter) Tfoot_(innerHtml func()) {
	w.WriteNormalElement("tfoot", nil, innerHtml)
}

func (w *HtmlWriter) Tr(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("tr", attrs, innerHtml)
}

func (w *HtmlWriter) Tr_(innerHtml func()) {
	w.WriteNormalElement("tr", nil, innerHtml)
}

func (w *HtmlWriter) Td(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("td", attrs, innerHtml)
}

func (w *HtmlWriter) Td_(innerHtml func()) {
	w.WriteNormalElement("td", nil, innerHtml)
}

func (w *HtmlWriter) Th(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("th", attrs, innerHtml)
}

func (w *HtmlWriter) Th_(innerHtml func()) {
	w.WriteNormalElement("th", nil, innerHtml)
}

func (w *HtmlWriter) Form(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("form", attrs, innerHtml)
}

func (w *HtmlWriter) Form_(innerHtml func()) {
	w.WriteNormalElement("form", nil, innerHtml)
}

func (w *HtmlWriter) Fieldset(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("fieldset", attrs, innerHtml)
}

func (w *HtmlWriter) Fieldset_(innerHtml func()) {
	w.WriteNormalElement("fieldset", nil, innerHtml)
}

func (w *HtmlWriter) Legend(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("legend", attrs, innerHtml)
}

func (w *HtmlWriter) Legend_(innerHtml func()) {
	w.WriteNormalElement("legend", nil, innerHtml)
}

func (w *HtmlWriter) Label(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("label", attrs, innerHtml)
}

func (w *HtmlWriter) Label_(innerHtml func()) {
	w.WriteNormalElement("label", nil, innerHtml)
}

func (w *HtmlWriter) Button(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("button", attrs, innerHtml)
}

func (w *HtmlWriter) Button_(innerHtml func()) {
	w.WriteNormalElement("button", nil, innerHtml)
}

func (w *HtmlWriter) Select(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("select", attrs, innerHtml)
}

func (w *HtmlWriter) Select_(innerHtml func()) {
	w.WriteNormalElement("select", nil, innerHtml)
}

func (w *HtmlWriter) Datalist(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("datalist", attrs, innerHtml)
}

func (w *HtmlWriter) Datalist_(innerHtml func()) {
	w.WriteNormalElement("datalist", nil, innerHtml)
}

func (w *HtmlWriter) Optgroup(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("optgroup", attrs, innerHtml)
}

func (w *HtmlWriter) Optgroup_(innerHtml func()) {
	w.WriteNormalElement("optgroup", nil, innerHtml)
}

func (w *HtmlWriter) Output(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("output", attrs, innerHtml)
}

func (w *HtmlWriter) Output_(innerHtml func()) {
	w.WriteNormalElement("output", nil, innerHtml)
}

func (w *HtmlWriter) Progress(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("progress", attrs, innerHtml)
}

func (w *HtmlWriter) Progress_(innerHtml func()) {
	w.WriteNormalElement("progress", nil, innerHtml)
}

func (w *HtmlWriter) Meter(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("meter", attrs, innerHtml)
}

func (w *HtmlWriter) Meter_(innerHtml func()) {
	w.WriteNormalElement("meter", nil, innerHtml)
}

func (w *HtmlWriter) Details(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("details", attrs, innerHtml)
}

func (w *HtmlWriter) Details_(innerHtml func()) {
	w.WriteNormalElement("details", nil, innerHtml)
}

func (w *HtmlWriter) Summary(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("summary", attrs, innerHtml)
}

func (w *HtmlWriter) Summary_(innerHtml func()) {
	w.WriteNormalElement("summary", nil, innerHtml)
}

func (w *HtmlWriter) Menu(attrs Attrs, innerHtml func()) {
	w.WriteNormalElement("menu", attrs, innerHtml)
}

func (w *HtmlWriter) Menu_(innerHtml func()) {
	w.WriteNormalElement("menu", nil, innerHtml)
}

