// This file was generated by the 'generate' Rake task

package htmlbuffer

func (b *HtmlBuffer) Head(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("head", attrs, innerHtml)
}

func (b *HtmlBuffer) Head_(innerHtml func()) {
	b.WriteNormalElement("head", nil, innerHtml)
}

func (b *HtmlBuffer) Title(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("title", attrs, innerHtml)
}

func (b *HtmlBuffer) Title_(innerHtml func()) {
	b.WriteNormalElement("title", nil, innerHtml)
}

func (b *HtmlBuffer) Style(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("style", attrs, innerHtml)
}

func (b *HtmlBuffer) Style_(innerHtml func()) {
	b.WriteNormalElement("style", nil, innerHtml)
}

func (b *HtmlBuffer) Script(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("script", attrs, innerHtml)
}

func (b *HtmlBuffer) Script_(innerHtml func()) {
	b.WriteNormalElement("script", nil, innerHtml)
}

func (b *HtmlBuffer) Noscript(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("noscript", attrs, innerHtml)
}

func (b *HtmlBuffer) Noscript_(innerHtml func()) {
	b.WriteNormalElement("noscript", nil, innerHtml)
}

func (b *HtmlBuffer) Body(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("body", attrs, innerHtml)
}

func (b *HtmlBuffer) Body_(innerHtml func()) {
	b.WriteNormalElement("body", nil, innerHtml)
}

func (b *HtmlBuffer) Section(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("section", attrs, innerHtml)
}

func (b *HtmlBuffer) Section_(innerHtml func()) {
	b.WriteNormalElement("section", nil, innerHtml)
}

func (b *HtmlBuffer) Nav(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("nav", attrs, innerHtml)
}

func (b *HtmlBuffer) Nav_(innerHtml func()) {
	b.WriteNormalElement("nav", nil, innerHtml)
}

func (b *HtmlBuffer) Article(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("article", attrs, innerHtml)
}

func (b *HtmlBuffer) Article_(innerHtml func()) {
	b.WriteNormalElement("article", nil, innerHtml)
}

func (b *HtmlBuffer) Aside(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("aside", attrs, innerHtml)
}

func (b *HtmlBuffer) Aside_(innerHtml func()) {
	b.WriteNormalElement("aside", nil, innerHtml)
}

func (b *HtmlBuffer) H1(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("h1", attrs, innerHtml)
}

func (b *HtmlBuffer) H1_(innerHtml func()) {
	b.WriteNormalElement("h1", nil, innerHtml)
}

func (b *HtmlBuffer) H2(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("h2", attrs, innerHtml)
}

func (b *HtmlBuffer) H2_(innerHtml func()) {
	b.WriteNormalElement("h2", nil, innerHtml)
}

func (b *HtmlBuffer) H3(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("h3", attrs, innerHtml)
}

func (b *HtmlBuffer) H3_(innerHtml func()) {
	b.WriteNormalElement("h3", nil, innerHtml)
}

func (b *HtmlBuffer) H4(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("h4", attrs, innerHtml)
}

func (b *HtmlBuffer) H4_(innerHtml func()) {
	b.WriteNormalElement("h4", nil, innerHtml)
}

func (b *HtmlBuffer) H5(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("h5", attrs, innerHtml)
}

func (b *HtmlBuffer) H5_(innerHtml func()) {
	b.WriteNormalElement("h5", nil, innerHtml)
}

func (b *HtmlBuffer) H6(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("h6", attrs, innerHtml)
}

func (b *HtmlBuffer) H6_(innerHtml func()) {
	b.WriteNormalElement("h6", nil, innerHtml)
}

func (b *HtmlBuffer) Header(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("header", attrs, innerHtml)
}

func (b *HtmlBuffer) Header_(innerHtml func()) {
	b.WriteNormalElement("header", nil, innerHtml)
}

func (b *HtmlBuffer) Footer(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("footer", attrs, innerHtml)
}

func (b *HtmlBuffer) Footer_(innerHtml func()) {
	b.WriteNormalElement("footer", nil, innerHtml)
}

func (b *HtmlBuffer) Address(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("address", attrs, innerHtml)
}

func (b *HtmlBuffer) Address_(innerHtml func()) {
	b.WriteNormalElement("address", nil, innerHtml)
}

func (b *HtmlBuffer) Main(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("main", attrs, innerHtml)
}

func (b *HtmlBuffer) Main_(innerHtml func()) {
	b.WriteNormalElement("main", nil, innerHtml)
}

func (b *HtmlBuffer) P(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("p", attrs, innerHtml)
}

func (b *HtmlBuffer) P_(innerHtml func()) {
	b.WriteNormalElement("p", nil, innerHtml)
}

func (b *HtmlBuffer) Pre(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("pre", attrs, innerHtml)
}

func (b *HtmlBuffer) Pre_(innerHtml func()) {
	b.WriteNormalElement("pre", nil, innerHtml)
}

func (b *HtmlBuffer) Blockquote(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("blockquote", attrs, innerHtml)
}

func (b *HtmlBuffer) Blockquote_(innerHtml func()) {
	b.WriteNormalElement("blockquote", nil, innerHtml)
}

func (b *HtmlBuffer) Ol(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("ol", attrs, innerHtml)
}

func (b *HtmlBuffer) Ol_(innerHtml func()) {
	b.WriteNormalElement("ol", nil, innerHtml)
}

func (b *HtmlBuffer) Ul(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("ul", attrs, innerHtml)
}

func (b *HtmlBuffer) Ul_(innerHtml func()) {
	b.WriteNormalElement("ul", nil, innerHtml)
}

func (b *HtmlBuffer) Li(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("li", attrs, innerHtml)
}

func (b *HtmlBuffer) Li_(innerHtml func()) {
	b.WriteNormalElement("li", nil, innerHtml)
}

func (b *HtmlBuffer) Dl(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("dl", attrs, innerHtml)
}

func (b *HtmlBuffer) Dl_(innerHtml func()) {
	b.WriteNormalElement("dl", nil, innerHtml)
}

func (b *HtmlBuffer) Dt(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("dt", attrs, innerHtml)
}

func (b *HtmlBuffer) Dt_(innerHtml func()) {
	b.WriteNormalElement("dt", nil, innerHtml)
}

func (b *HtmlBuffer) Dd(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("dd", attrs, innerHtml)
}

func (b *HtmlBuffer) Dd_(innerHtml func()) {
	b.WriteNormalElement("dd", nil, innerHtml)
}

func (b *HtmlBuffer) Figure(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("figure", attrs, innerHtml)
}

func (b *HtmlBuffer) Figure_(innerHtml func()) {
	b.WriteNormalElement("figure", nil, innerHtml)
}

func (b *HtmlBuffer) Figcaption(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("figcaption", attrs, innerHtml)
}

func (b *HtmlBuffer) Figcaption_(innerHtml func()) {
	b.WriteNormalElement("figcaption", nil, innerHtml)
}

func (b *HtmlBuffer) Div(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("div", attrs, innerHtml)
}

func (b *HtmlBuffer) Div_(innerHtml func()) {
	b.WriteNormalElement("div", nil, innerHtml)
}

func (b *HtmlBuffer) A(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("a", attrs, innerHtml)
}

func (b *HtmlBuffer) A_(innerHtml func()) {
	b.WriteNormalElement("a", nil, innerHtml)
}

func (b *HtmlBuffer) Em(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("em", attrs, innerHtml)
}

func (b *HtmlBuffer) Em_(innerHtml func()) {
	b.WriteNormalElement("em", nil, innerHtml)
}

func (b *HtmlBuffer) Strong(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("strong", attrs, innerHtml)
}

func (b *HtmlBuffer) Strong_(innerHtml func()) {
	b.WriteNormalElement("strong", nil, innerHtml)
}

func (b *HtmlBuffer) Small(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("small", attrs, innerHtml)
}

func (b *HtmlBuffer) Small_(innerHtml func()) {
	b.WriteNormalElement("small", nil, innerHtml)
}

func (b *HtmlBuffer) S(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("s", attrs, innerHtml)
}

func (b *HtmlBuffer) S_(innerHtml func()) {
	b.WriteNormalElement("s", nil, innerHtml)
}

func (b *HtmlBuffer) Cite(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("cite", attrs, innerHtml)
}

func (b *HtmlBuffer) Cite_(innerHtml func()) {
	b.WriteNormalElement("cite", nil, innerHtml)
}

func (b *HtmlBuffer) Q(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("q", attrs, innerHtml)
}

func (b *HtmlBuffer) Q_(innerHtml func()) {
	b.WriteNormalElement("q", nil, innerHtml)
}

func (b *HtmlBuffer) Dfn(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("dfn", attrs, innerHtml)
}

func (b *HtmlBuffer) Dfn_(innerHtml func()) {
	b.WriteNormalElement("dfn", nil, innerHtml)
}

func (b *HtmlBuffer) Abbr(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("abbr", attrs, innerHtml)
}

func (b *HtmlBuffer) Abbr_(innerHtml func()) {
	b.WriteNormalElement("abbr", nil, innerHtml)
}

func (b *HtmlBuffer) Data(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("data", attrs, innerHtml)
}

func (b *HtmlBuffer) Data_(innerHtml func()) {
	b.WriteNormalElement("data", nil, innerHtml)
}

func (b *HtmlBuffer) Time(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("time", attrs, innerHtml)
}

func (b *HtmlBuffer) Time_(innerHtml func()) {
	b.WriteNormalElement("time", nil, innerHtml)
}

func (b *HtmlBuffer) Code(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("code", attrs, innerHtml)
}

func (b *HtmlBuffer) Code_(innerHtml func()) {
	b.WriteNormalElement("code", nil, innerHtml)
}

func (b *HtmlBuffer) Var(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("var", attrs, innerHtml)
}

func (b *HtmlBuffer) Var_(innerHtml func()) {
	b.WriteNormalElement("var", nil, innerHtml)
}

func (b *HtmlBuffer) Samp(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("samp", attrs, innerHtml)
}

func (b *HtmlBuffer) Samp_(innerHtml func()) {
	b.WriteNormalElement("samp", nil, innerHtml)
}

func (b *HtmlBuffer) Kbd(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("kbd", attrs, innerHtml)
}

func (b *HtmlBuffer) Kbd_(innerHtml func()) {
	b.WriteNormalElement("kbd", nil, innerHtml)
}

func (b *HtmlBuffer) Sub(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("sub", attrs, innerHtml)
}

func (b *HtmlBuffer) Sub_(innerHtml func()) {
	b.WriteNormalElement("sub", nil, innerHtml)
}

func (b *HtmlBuffer) Sup(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("sup", attrs, innerHtml)
}

func (b *HtmlBuffer) Sup_(innerHtml func()) {
	b.WriteNormalElement("sup", nil, innerHtml)
}

func (b *HtmlBuffer) I(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("i", attrs, innerHtml)
}

func (b *HtmlBuffer) I_(innerHtml func()) {
	b.WriteNormalElement("i", nil, innerHtml)
}

func (b *HtmlBuffer) B(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("b", attrs, innerHtml)
}

func (b *HtmlBuffer) B_(innerHtml func()) {
	b.WriteNormalElement("b", nil, innerHtml)
}

func (b *HtmlBuffer) U(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("u", attrs, innerHtml)
}

func (b *HtmlBuffer) U_(innerHtml func()) {
	b.WriteNormalElement("u", nil, innerHtml)
}

func (b *HtmlBuffer) Mark(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("mark", attrs, innerHtml)
}

func (b *HtmlBuffer) Mark_(innerHtml func()) {
	b.WriteNormalElement("mark", nil, innerHtml)
}

func (b *HtmlBuffer) Ruby(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("ruby", attrs, innerHtml)
}

func (b *HtmlBuffer) Ruby_(innerHtml func()) {
	b.WriteNormalElement("ruby", nil, innerHtml)
}

func (b *HtmlBuffer) Rt(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("rt", attrs, innerHtml)
}

func (b *HtmlBuffer) Rt_(innerHtml func()) {
	b.WriteNormalElement("rt", nil, innerHtml)
}

func (b *HtmlBuffer) Rp(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("rp", attrs, innerHtml)
}

func (b *HtmlBuffer) Rp_(innerHtml func()) {
	b.WriteNormalElement("rp", nil, innerHtml)
}

func (b *HtmlBuffer) Bdi(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("bdi", attrs, innerHtml)
}

func (b *HtmlBuffer) Bdi_(innerHtml func()) {
	b.WriteNormalElement("bdi", nil, innerHtml)
}

func (b *HtmlBuffer) Bdo(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("bdo", attrs, innerHtml)
}

func (b *HtmlBuffer) Bdo_(innerHtml func()) {
	b.WriteNormalElement("bdo", nil, innerHtml)
}

func (b *HtmlBuffer) Span(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("span", attrs, innerHtml)
}

func (b *HtmlBuffer) Span_(innerHtml func()) {
	b.WriteNormalElement("span", nil, innerHtml)
}

func (b *HtmlBuffer) Ins(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("ins", attrs, innerHtml)
}

func (b *HtmlBuffer) Ins_(innerHtml func()) {
	b.WriteNormalElement("ins", nil, innerHtml)
}

func (b *HtmlBuffer) Del(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("del", attrs, innerHtml)
}

func (b *HtmlBuffer) Del_(innerHtml func()) {
	b.WriteNormalElement("del", nil, innerHtml)
}

func (b *HtmlBuffer) Iframe(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("iframe", attrs, innerHtml)
}

func (b *HtmlBuffer) Iframe_(innerHtml func()) {
	b.WriteNormalElement("iframe", nil, innerHtml)
}

func (b *HtmlBuffer) Object(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("object", attrs, innerHtml)
}

func (b *HtmlBuffer) Object_(innerHtml func()) {
	b.WriteNormalElement("object", nil, innerHtml)
}

func (b *HtmlBuffer) Video(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("video", attrs, innerHtml)
}

func (b *HtmlBuffer) Video_(innerHtml func()) {
	b.WriteNormalElement("video", nil, innerHtml)
}

func (b *HtmlBuffer) Audio(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("audio", attrs, innerHtml)
}

func (b *HtmlBuffer) Audio_(innerHtml func()) {
	b.WriteNormalElement("audio", nil, innerHtml)
}

func (b *HtmlBuffer) Canvas(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("canvas", attrs, innerHtml)
}

func (b *HtmlBuffer) Canvas_(innerHtml func()) {
	b.WriteNormalElement("canvas", nil, innerHtml)
}

func (b *HtmlBuffer) Map(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("map", attrs, innerHtml)
}

func (b *HtmlBuffer) Map_(innerHtml func()) {
	b.WriteNormalElement("map", nil, innerHtml)
}

func (b *HtmlBuffer) Svg(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("svg", attrs, innerHtml)
}

func (b *HtmlBuffer) Svg_(innerHtml func()) {
	b.WriteNormalElement("svg", nil, innerHtml)
}

func (b *HtmlBuffer) Math(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("math", attrs, innerHtml)
}

func (b *HtmlBuffer) Math_(innerHtml func()) {
	b.WriteNormalElement("math", nil, innerHtml)
}

func (b *HtmlBuffer) Table(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("table", attrs, innerHtml)
}

func (b *HtmlBuffer) Table_(innerHtml func()) {
	b.WriteNormalElement("table", nil, innerHtml)
}

func (b *HtmlBuffer) Caption(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("caption", attrs, innerHtml)
}

func (b *HtmlBuffer) Caption_(innerHtml func()) {
	b.WriteNormalElement("caption", nil, innerHtml)
}

func (b *HtmlBuffer) Colgroup(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("colgroup", attrs, innerHtml)
}

func (b *HtmlBuffer) Colgroup_(innerHtml func()) {
	b.WriteNormalElement("colgroup", nil, innerHtml)
}

func (b *HtmlBuffer) Tbody(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("tbody", attrs, innerHtml)
}

func (b *HtmlBuffer) Tbody_(innerHtml func()) {
	b.WriteNormalElement("tbody", nil, innerHtml)
}

func (b *HtmlBuffer) Thead(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("thead", attrs, innerHtml)
}

func (b *HtmlBuffer) Thead_(innerHtml func()) {
	b.WriteNormalElement("thead", nil, innerHtml)
}

func (b *HtmlBuffer) Tfoot(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("tfoot", attrs, innerHtml)
}

func (b *HtmlBuffer) Tfoot_(innerHtml func()) {
	b.WriteNormalElement("tfoot", nil, innerHtml)
}

func (b *HtmlBuffer) Tr(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("tr", attrs, innerHtml)
}

func (b *HtmlBuffer) Tr_(innerHtml func()) {
	b.WriteNormalElement("tr", nil, innerHtml)
}

func (b *HtmlBuffer) Td(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("td", attrs, innerHtml)
}

func (b *HtmlBuffer) Td_(innerHtml func()) {
	b.WriteNormalElement("td", nil, innerHtml)
}

func (b *HtmlBuffer) Th(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("th", attrs, innerHtml)
}

func (b *HtmlBuffer) Th_(innerHtml func()) {
	b.WriteNormalElement("th", nil, innerHtml)
}

func (b *HtmlBuffer) Form(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("form", attrs, innerHtml)
}

func (b *HtmlBuffer) Form_(innerHtml func()) {
	b.WriteNormalElement("form", nil, innerHtml)
}

func (b *HtmlBuffer) Fieldset(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("fieldset", attrs, innerHtml)
}

func (b *HtmlBuffer) Fieldset_(innerHtml func()) {
	b.WriteNormalElement("fieldset", nil, innerHtml)
}

func (b *HtmlBuffer) Legend(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("legend", attrs, innerHtml)
}

func (b *HtmlBuffer) Legend_(innerHtml func()) {
	b.WriteNormalElement("legend", nil, innerHtml)
}

func (b *HtmlBuffer) Label(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("label", attrs, innerHtml)
}

func (b *HtmlBuffer) Label_(innerHtml func()) {
	b.WriteNormalElement("label", nil, innerHtml)
}

func (b *HtmlBuffer) Button(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("button", attrs, innerHtml)
}

func (b *HtmlBuffer) Button_(innerHtml func()) {
	b.WriteNormalElement("button", nil, innerHtml)
}

func (b *HtmlBuffer) Select(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("select", attrs, innerHtml)
}

func (b *HtmlBuffer) Select_(innerHtml func()) {
	b.WriteNormalElement("select", nil, innerHtml)
}

func (b *HtmlBuffer) Datalist(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("datalist", attrs, innerHtml)
}

func (b *HtmlBuffer) Datalist_(innerHtml func()) {
	b.WriteNormalElement("datalist", nil, innerHtml)
}

func (b *HtmlBuffer) Optgroup(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("optgroup", attrs, innerHtml)
}

func (b *HtmlBuffer) Optgroup_(innerHtml func()) {
	b.WriteNormalElement("optgroup", nil, innerHtml)
}

func (b *HtmlBuffer) Option(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("option", attrs, innerHtml)
}

func (b *HtmlBuffer) Option_(innerHtml func()) {
	b.WriteNormalElement("option", nil, innerHtml)
}

func (b *HtmlBuffer) Textarea(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("textarea", attrs, innerHtml)
}

func (b *HtmlBuffer) Textarea_(innerHtml func()) {
	b.WriteNormalElement("textarea", nil, innerHtml)
}

func (b *HtmlBuffer) Output(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("output", attrs, innerHtml)
}

func (b *HtmlBuffer) Output_(innerHtml func()) {
	b.WriteNormalElement("output", nil, innerHtml)
}

func (b *HtmlBuffer) Progress(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("progress", attrs, innerHtml)
}

func (b *HtmlBuffer) Progress_(innerHtml func()) {
	b.WriteNormalElement("progress", nil, innerHtml)
}

func (b *HtmlBuffer) Meter(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("meter", attrs, innerHtml)
}

func (b *HtmlBuffer) Meter_(innerHtml func()) {
	b.WriteNormalElement("meter", nil, innerHtml)
}

func (b *HtmlBuffer) Details(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("details", attrs, innerHtml)
}

func (b *HtmlBuffer) Details_(innerHtml func()) {
	b.WriteNormalElement("details", nil, innerHtml)
}

func (b *HtmlBuffer) Summary(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("summary", attrs, innerHtml)
}

func (b *HtmlBuffer) Summary_(innerHtml func()) {
	b.WriteNormalElement("summary", nil, innerHtml)
}

func (b *HtmlBuffer) Menu(attrs Attrs, innerHtml func()) {
	b.WriteNormalElement("menu", attrs, innerHtml)
}

func (b *HtmlBuffer) Menu_(innerHtml func()) {
	b.WriteNormalElement("menu", nil, innerHtml)
}

