// This file was generated by the 'generate' Rake task

package htmlwriter

func (w *HtmlWriter) Title(attrs Attrs, formatStr string, a ...interface{}) {
	w.WriteNormalElement("title", attrs, w.RawTextF(formatStr, a...))
}

func (w *HtmlWriter) Title_(formatStr string, a ...interface{}) {
	w.WriteNormalElement("title", nil, w.RawTextF(formatStr, a...))
}

func (w *HtmlWriter) Option(attrs Attrs, formatStr string, a ...interface{}) {
	w.WriteNormalElement("option", attrs, w.RawTextF(formatStr, a...))
}

func (w *HtmlWriter) Option_(formatStr string, a ...interface{}) {
	w.WriteNormalElement("option", nil, w.RawTextF(formatStr, a...))
}

func (w *HtmlWriter) Textarea(attrs Attrs, formatStr string, a ...interface{}) {
	w.WriteNormalElement("textarea", attrs, w.RawTextF(formatStr, a...))
}

func (w *HtmlWriter) Textarea_(formatStr string, a ...interface{}) {
	w.WriteNormalElement("textarea", nil, w.RawTextF(formatStr, a...))
}

