// This file was generated by the 'generate' Rake task

package htmlbuffer

func (b *HtmlBuffer) ButtonInput(attrs Attrs) {
	attrs["type"] = "button"
	b.Input(attrs)
}

func (b *HtmlBuffer) ButtonInput_() {
	b.Input(Attrs{"type": "button"})
}

func (b *HtmlBuffer) CheckboxInput(attrs Attrs) {
	attrs["type"] = "checkbox"
	b.Input(attrs)
}

func (b *HtmlBuffer) CheckboxInput_() {
	b.Input(Attrs{"type": "checkbox"})
}

func (b *HtmlBuffer) ColorInput(attrs Attrs) {
	attrs["type"] = "color"
	b.Input(attrs)
}

func (b *HtmlBuffer) ColorInput_() {
	b.Input(Attrs{"type": "color"})
}

func (b *HtmlBuffer) DateInput(attrs Attrs) {
	attrs["type"] = "date"
	b.Input(attrs)
}

func (b *HtmlBuffer) DateInput_() {
	b.Input(Attrs{"type": "date"})
}

func (b *HtmlBuffer) DatetimeInput(attrs Attrs) {
	attrs["type"] = "datetime"
	b.Input(attrs)
}

func (b *HtmlBuffer) DatetimeInput_() {
	b.Input(Attrs{"type": "datetime"})
}

func (b *HtmlBuffer) DatetimeLocalInput(attrs Attrs) {
	attrs["type"] = "datetime-local"
	b.Input(attrs)
}

func (b *HtmlBuffer) DatetimeLocalInput_() {
	b.Input(Attrs{"type": "datetime-local"})
}

func (b *HtmlBuffer) EmailInput(attrs Attrs) {
	attrs["type"] = "email"
	b.Input(attrs)
}

func (b *HtmlBuffer) EmailInput_() {
	b.Input(Attrs{"type": "email"})
}

func (b *HtmlBuffer) FileInput(attrs Attrs) {
	attrs["type"] = "file"
	b.Input(attrs)
}

func (b *HtmlBuffer) FileInput_() {
	b.Input(Attrs{"type": "file"})
}

func (b *HtmlBuffer) HiddenInput(attrs Attrs) {
	attrs["type"] = "hidden"
	b.Input(attrs)
}

func (b *HtmlBuffer) HiddenInput_() {
	b.Input(Attrs{"type": "hidden"})
}

func (b *HtmlBuffer) ImageInput(attrs Attrs) {
	attrs["type"] = "image"
	b.Input(attrs)
}

func (b *HtmlBuffer) ImageInput_() {
	b.Input(Attrs{"type": "image"})
}

func (b *HtmlBuffer) MonthInput(attrs Attrs) {
	attrs["type"] = "month"
	b.Input(attrs)
}

func (b *HtmlBuffer) MonthInput_() {
	b.Input(Attrs{"type": "month"})
}

func (b *HtmlBuffer) NumberInput(attrs Attrs) {
	attrs["type"] = "number"
	b.Input(attrs)
}

func (b *HtmlBuffer) NumberInput_() {
	b.Input(Attrs{"type": "number"})
}

func (b *HtmlBuffer) PasswordInput(attrs Attrs) {
	attrs["type"] = "password"
	b.Input(attrs)
}

func (b *HtmlBuffer) PasswordInput_() {
	b.Input(Attrs{"type": "password"})
}

func (b *HtmlBuffer) RadioInput(attrs Attrs) {
	attrs["type"] = "radio"
	b.Input(attrs)
}

func (b *HtmlBuffer) RadioInput_() {
	b.Input(Attrs{"type": "radio"})
}

func (b *HtmlBuffer) RangeInput(attrs Attrs) {
	attrs["type"] = "range"
	b.Input(attrs)
}

func (b *HtmlBuffer) RangeInput_() {
	b.Input(Attrs{"type": "range"})
}

func (b *HtmlBuffer) ResetInput(attrs Attrs) {
	attrs["type"] = "reset"
	b.Input(attrs)
}

func (b *HtmlBuffer) ResetInput_() {
	b.Input(Attrs{"type": "reset"})
}

func (b *HtmlBuffer) SearchInput(attrs Attrs) {
	attrs["type"] = "search"
	b.Input(attrs)
}

func (b *HtmlBuffer) SearchInput_() {
	b.Input(Attrs{"type": "search"})
}

func (b *HtmlBuffer) SubmitInput(attrs Attrs) {
	attrs["type"] = "submit"
	b.Input(attrs)
}

func (b *HtmlBuffer) SubmitInput_() {
	b.Input(Attrs{"type": "submit"})
}

func (b *HtmlBuffer) TelInput(attrs Attrs) {
	attrs["type"] = "tel"
	b.Input(attrs)
}

func (b *HtmlBuffer) TelInput_() {
	b.Input(Attrs{"type": "tel"})
}

func (b *HtmlBuffer) TextInput(attrs Attrs) {
	attrs["type"] = "text"
	b.Input(attrs)
}

func (b *HtmlBuffer) TextInput_() {
	b.Input(Attrs{"type": "text"})
}

func (b *HtmlBuffer) TimeInput(attrs Attrs) {
	attrs["type"] = "time"
	b.Input(attrs)
}

func (b *HtmlBuffer) TimeInput_() {
	b.Input(Attrs{"type": "time"})
}

func (b *HtmlBuffer) UrlInput(attrs Attrs) {
	attrs["type"] = "url"
	b.Input(attrs)
}

func (b *HtmlBuffer) UrlInput_() {
	b.Input(Attrs{"type": "url"})
}

func (b *HtmlBuffer) WeekInput(attrs Attrs) {
	attrs["type"] = "week"
	b.Input(attrs)
}

func (b *HtmlBuffer) WeekInput_() {
	b.Input(Attrs{"type": "week"})
}

