// This file was generated by the 'generate' Rake task

package htmlwriter

func (w *HtmlWriter) Base(attrs Attrs) {
	w.WriteVoidElement("base", attrs)
}

func (w *HtmlWriter) Base_() {
	w.WriteVoidElement("base", nil)
}

func (w *HtmlWriter) Link(attrs Attrs) {
	w.WriteVoidElement("link", attrs)
}

func (w *HtmlWriter) Link_() {
	w.WriteVoidElement("link", nil)
}

func (w *HtmlWriter) Meta(attrs Attrs) {
	w.WriteVoidElement("meta", attrs)
}

func (w *HtmlWriter) Meta_() {
	w.WriteVoidElement("meta", nil)
}

func (w *HtmlWriter) Hr(attrs Attrs) {
	w.WriteVoidElement("hr", attrs)
}

func (w *HtmlWriter) Hr_() {
	w.WriteVoidElement("hr", nil)
}

func (w *HtmlWriter) Br(attrs Attrs) {
	w.WriteVoidElement("br", attrs)
}

func (w *HtmlWriter) Br_() {
	w.WriteVoidElement("br", nil)
}

func (w *HtmlWriter) Wbr(attrs Attrs) {
	w.WriteVoidElement("wbr", attrs)
}

func (w *HtmlWriter) Wbr_() {
	w.WriteVoidElement("wbr", nil)
}

func (w *HtmlWriter) Input(attrs Attrs) {
	w.WriteVoidElement("input", attrs)
}

func (w *HtmlWriter) Input_() {
	w.WriteVoidElement("input", nil)
}

func (w *HtmlWriter) Area(attrs Attrs) {
	w.WriteVoidElement("area", attrs)
}

func (w *HtmlWriter) Area_() {
	w.WriteVoidElement("area", nil)
}

func (w *HtmlWriter) Command(attrs Attrs) {
	w.WriteVoidElement("command", attrs)
}

func (w *HtmlWriter) Command_() {
	w.WriteVoidElement("command", nil)
}

func (w *HtmlWriter) Col(attrs Attrs) {
	w.WriteVoidElement("col", attrs)
}

func (w *HtmlWriter) Col_() {
	w.WriteVoidElement("col", nil)
}

func (w *HtmlWriter) Img(attrs Attrs) {
	w.WriteVoidElement("img", attrs)
}

func (w *HtmlWriter) Img_() {
	w.WriteVoidElement("img", nil)
}

func (w *HtmlWriter) Keygen(attrs Attrs) {
	w.WriteVoidElement("keygen", attrs)
}

func (w *HtmlWriter) Keygen_() {
	w.WriteVoidElement("keygen", nil)
}

func (w *HtmlWriter) Param(attrs Attrs) {
	w.WriteVoidElement("param", attrs)
}

func (w *HtmlWriter) Param_() {
	w.WriteVoidElement("param", nil)
}

func (w *HtmlWriter) Source(attrs Attrs) {
	w.WriteVoidElement("source", attrs)
}

func (w *HtmlWriter) Source_() {
	w.WriteVoidElement("source", nil)
}

func (w *HtmlWriter) Track(attrs Attrs) {
	w.WriteVoidElement("track", attrs)
}

func (w *HtmlWriter) Track_() {
	w.WriteVoidElement("track", nil)
}

func (w *HtmlWriter) Embed(attrs Attrs) {
	w.WriteVoidElement("embed", attrs)
}

func (w *HtmlWriter) Embed_() {
	w.WriteVoidElement("embed", nil)
}

