// This file was generated by the 'generate' Rake task

package htmlbuffer

func (b *HtmlBuffer) Title(attrs Attrs, text string) {
	b.WriteNormalElement("title", attrs, b.TextF(text))
}

func (b *HtmlBuffer) Title_(text string) {
	b.WriteNormalElement("title", nil, b.TextF(text))
}

func (b *HtmlBuffer) Option(attrs Attrs, text string) {
	b.WriteNormalElement("option", attrs, b.TextF(text))
}

func (b *HtmlBuffer) Option_(text string) {
	b.WriteNormalElement("option", nil, b.TextF(text))
}

func (b *HtmlBuffer) Textarea(attrs Attrs, text string) {
	b.WriteNormalElement("textarea", attrs, b.TextF(text))
}

func (b *HtmlBuffer) Textarea_(text string) {
	b.WriteNormalElement("textarea", nil, b.TextF(text))
}

